name: Main Action
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**'
    types: [opened, synchronize, reopened]
    branches:
      - main
jobs:
  coverage-check-main-pr:
    name: Sonar Analysis Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Disables shallow clones for a better relevancy of analysis
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu' # Alternative distribution options are available.  distribution is required
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        run: mvn -B verify
      - name: Report Coveralls (Linux)
        run: curl -sL https://coveralls.io/coveralls-linux.tar.gz | tar -xz && ./coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
